[phases.setup]
nixpkgsArchive = '23f9169c4ccce521379e602cc82ed873a1f1b52b'
pkgs = ['nodejs_20', 'openssl']
nixLibs = ['libvips']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build -w @inboxflow/api']

[phases.start]
cmds = ['NODE_OPTIONS="--max-old-space-size=384 --v8-flags=--lazy-eval" npm run start -w @inboxflow/api']
